baseurl: "/"
languageCode: "zh-cn"
title: "罗泽勋"
theme: "hugo-paper"
googleAnalytics: "G-KDTTBGMLCQ"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableInlineShortcodes: true
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100
ignoreErrors: ["error-remote-getjson"]

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"
  blog: "/blog/:year/:month/:day/:slug/"

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/blog/"
      weight: 3
    - name: "编程"
      url: "/post/"
      weight: 4
    - name: "收录"
      url: "/collection/"
      weight: 5
    - name: "分类"
      url: "/categories/"
      weight: 6
    # - name: "简历"
    #   url: "/vitae/"
    #   weight: 7

params:
  # twitter: 'lzxqaq'
  github: 'lzxqaq'
  # instagram: 'lzxqaq'
  description: "糸色先生"
  footer: "&copy; [Zexun Luo](/) 2020 - 2022 "
  disqusURL: "/"
  
  utteranc:
    enable: true
    repo: "lzxqaq/site-comment"
    issueTerm: "title"
    theme: "github-light"

  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "Zexun Luo"
    tag: ""

  author:
    en: "Zexun Luo"
    cn: "糸色先生"
    

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
