baseurl: "/"
languageCode: "zh-cn"
title: "闻道书斋"
theme: "hugo-lzx"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100



menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/post/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    - name: "作品"
      url: "/work/"
      weight: 5


params:
  description: "我的个人网站"
  footer: "&copy; [Zexun Luo](/) 2020 - 2021"
  disqusURL: "/"
  customJS:
    - "js/center-img.js"

  record:
    recordId: "粤ICP备 2021000668 号"
    recordUrl: "https://beian.miit.gov.cn"

  mastheadtype:

  logo:
    img: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/logo.png"
    url: "/"
    alt: "狂人笔记"
    tag: ""
    bgImg: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/bg.jpg"


  author:
    en: "Zexun Luo"
    cn: "罗泽勋"

  music:
    - name: "Shakira - Try Everything"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/Shakira_Try_Everything.mp3"
    - name: "周杰伦 - 爱的飞行日记"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/周杰伦_爱的飞行日记.mp3"
    - name: "王菲 - 当时的月亮"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/王菲_当时的月亮.mp3"
    - name: "アルプスの少女ハイジ - OP"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/HD_アルプスの少女ハイジ_OP.mp3"
    - name: "林子祥 - 男儿当自强"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/林子祥_男儿当自强.mp3"
    - name: "张国荣 - 春夏秋冬"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/张国荣_春夏秋冬.mp3"
    - name: "Frozen - Love is an Open Door"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/Frozen-Love_is_an_Open_Door.mp3"
        

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
