baseurl: "/"
languageCode: "zh-cn"
title: "罗泽勋"
theme: "hugo-xmin"
googleAnalytics: "G-KDTTBGMLCQ"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

taxonomies:
  category: categories
  tag: tags
  series: series

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"
  blog: "/blog/:year/:month/:day/:slug/"

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/blog/"
      weight: 3
    - name: "编程"
      url: "/post/"
      weight: 4
    - name: "标签"
      url: "/series/"
      weight: 5
    - name: "分类"
      url: "/categories/"
      weight: 6
    - name: "音乐"
      url: "/music/"
      weight: 7
    - name: "抄录"
      url: "/note/"
      weight: 8


params:
  description: "罗泽勋的个人网站"
  footer: "&copy; [Zexun Luo](/) 2020 - 2021 "
  customJS:
    - "js/center-img.js"
  utteranc:
    enable: true
    repo: "lzxqaq/site-comment"
    issueTerm: "title"
    theme: "github-light"

  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "Zexun Luo"
    tag: ""

  author:
    en: "Zexun Luo"
    cn: "罗泽勋"
  twitterImage: "/images/logo.png"
  
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
