baseurl: /
languageCode: zh-cn
title: 沙加
theme: hugo-ivy
googleAnalytics: "G-KDTTBGMLCQ"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
enableGitInfo: true

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
  blog: /blog/:year/:month/:day/:slug/

taxonomies:
  category: categories
  tag: tags


menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "归档"
      url: "/posts"
      weight: 2
    - name: "日常"
      url: "/todos"
      weight: 3      
    - name: "关于"
      url: "/about/"
      weight: 4
    - name: "标签"
      url: "/tags"
      weight: 5
    - name: "订阅"
      url: "/index.xml"

params:
  description: "我唯一知道的是我一无所知。"
  footer: "&copy; [Zexun Luo](https://lzxqaq.com) 2020-{Year} | [Github](https://github.com/lzxqaq)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
