baseurl: "/"
languageCode: "zh-cn"
title: "Zexun Luo | 罗泽勋"
theme: "hugo-xmin"
googleAnalytics: "G-KDTTBGMLCQ"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"
  blog: "/blog/:year/:month/:day/:slug/"

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/blog/"
      weight: 3
    - name: "编程"
      url: "/post/"
      weight: 4
    - name: "标签"
      url: "/series/"
      weight: 5
    - name: "分类"
      url: "/categories/"
      weight: 6
    - name: "简历"
      url: "/cv/"
      weight: 7
    - name: "抄录"
      url: "/note/"
      weight: 8
    - name: "事务"
      url: "/todo/"
      weight: 9


params:
  description: "罗泽勋的个人网站"
  footer: "&copy; [Zexun Luo](/) 2020 - 2022 "
  disqusURL: "/"
  customJS:
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/external-link.js"
    - "js/alt-title.js"
  
  utteranc:
    enable: true
    repo: "lzxqaq/site-comment"
    issueTerm: "title"
    theme: "github-light"

  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "Zexun Luo"
    tag: ""

  author:
    en: "Zexun Luo"
    cn: "罗泽勋"
    

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
