baseurl: "/"
languageCode: "zh-cn"
title: "人类生活见闻录"
theme: "hugo-lzx"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100



menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/post/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    - name: "作品"
      url: "/work/"
      weight: 5
    # - name: "简历"
    #   url: "/cv/"
    #   weight: 6

params:
  description: "我的个人网站"
  footer: "&copy; [Zexun Luo](/) 2020 - 2021"
  disqusURL: "/"
  customJS:
    - "js/center-img.js"
    - "js/external-link.js"

  logo:
    img: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/logo2.png"
    url: "/"
    alt: "狂人笔记"
    tag: ""
    bgImg: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/bg5.jpg"

  author:
    en: "Zexun Luo"
    cn: "罗泽勋"

  music:
    - name: "宗次郎 - いつも何度でも"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/宗次郎%20-%20いつも何度でも.mp3"
    - name: "岁月"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/岁月.mp3"
    - name: "张雨生 - 我的未来不是梦"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/张雨生 - 我的未来不是梦.mp3"
    - name: "自然卷 - How much"
      url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/自然卷%20-%20How%20much.mp3"
        

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
