baseurl: "/"
languageCode: "zh-cn"
title: "狂人笔记"
theme: "hugo-lzx"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100



menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/post/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    - name: "作品"
      url: "/work/"
      weight: 5
    # - name: "简历"
    #   url: "/cv/"
    #   weight: 6

params:
  description: "我的个人网站"
  footer: "&copy; [狂人笔记](/) 2020 - 2021"
  disqusURL: "/"


  logo:
    img: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/logo2.png"
    url: "/"
    alt: "狂人笔记"
    tag: ""
    bgImg: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/image/bg5.jpg"

  author:
    en: "Zexun Luo"
    cn: "罗泽勋"

  music:
      - name: "永远同在"
        url: "https://cdn.jsdelivr.net/gh/lzxqaq/jsdelivr@master/music/永远同在.mp3"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
