baseurl: "/"
languageCode: "zh-cn"
title: "闻道书斋"
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100



menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/blog/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    - name: "作品"
      url: "/work/"
      weight: 5


params:
  description: "罗泽勋的个人网站"
  footer: "&copy; [Zexun Luo](/) 2020 - 2021 "
  disqusURL: "/"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/rbind/yihui/edit/master/content/"
  twitterImage: "/images/logo.png"


    # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"


  logo:
    img: "/images/logo.png"
    url: "/"
    alt: "Zexun Luo"
    tag: ""

  author:
    en: "Zexun Luo"
    cn: "罗泽勋"
    
  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
